microsoft/vscode-azure-iot-toolkit

package.json
=> Add 'Azure' to command category

package-lock.json, package.json
Update azure-iothub to fix #89
=> Fix security vulnerability and #89

CHANGELOG.md, src/extension.ts, src/providers/deviceTwinCodeLensProvider.ts, src/providers/moduleTwinCodeLensProvider.ts
=> Add CodeLens to update Device/Module Twin

package.json, resources/code-template/http/sendD2C.http, resources/code-template/node/monitorD2C.js, resources/code-template/node/sendD2C.js, resources/code-template/python/sendD2C.py, src/azureIoTExplorer.ts, src/codeManager.ts, src/constants.ts, src/extension.ts, src/iotEdgeExplorer.ts
Generate code for Node.js, Python and HTTP.
=>  Generate Code

package.json, src/Model/ModuleItem.ts, src/azureIoTExplorer.ts, src/constants.ts, src/extension.ts, src/iotHubModuleExplorer.ts, src/telemetryClient.ts, src/utility.ts, test/utility.test.ts
* Get Module Info
* Copy Module Connection String
* Add IoTHubHostNamePostfix property in BI event
=> Get module info, copy module connection string

src/iotHubResourceExplorer.ts
I decided to just display information message, when there are no subscriptions available, hopefully it's user friendly.
=> (GH-67) Display friendly info when no subscriptions are available

src/iotHubMessageExplorer.ts, src/utility.ts
Add deviceType property to telemetry in order to get IoT Edge related usage
=> Add device type to telemetry

src/extension.ts, src/nsat.ts, src/telemetryClient.ts
=> Add NSAT survey

src/telemetryClient.ts
Update NSAT logic to filter IoT Workbench users
Filter load device tree event to send survey to more engaged users
=> Update NSAT logic to filter IoT Workbench users

package.json, src/iotEdgeExplorer.ts, src/iotHubDirectMethodExplorer.ts
* [Direct method] Support passing JSON in payload
* Add 'Refresh' into context menu of normal device
* Support deployment for multi-arch
=> Enhancement and support for multi-arch

package.json, resources/iot-hub-connection-string.md, src/constants.ts, src/utility.ts
When input a wrong format and press `Enter`, the markdown will show.
=> Better hint user when they fail to set IoT Hub connection string

package.json, src/deviceTree.ts, src/iotEdgeExplorer.ts
=>  Better hint user when loading tree failed

package.json, src/iotHubMessageExplorer.ts, webpack.config.js
* Resolve #237: Disable webpack minimize to make 'constructor.name' work
* Resolve #238: Add hint when stopping monitoring D2C message
=> Resolve #237 and #238

package-lock.json, package.json, webpack.config.js
=> Keep function names when minifying

.vscodeignore, package-lock.json, package.json, src/azureIoTExplorer.ts, src/extension.ts, src/iotHubModuleExplorer.ts, src/iotHubResourceExplorer.ts, webpack.config.js
Close https://github.com/Microsoft/vscode-azure-iot-toolkit/issues/248
=> Switch to VS Code built-in clipboard API

package-lock.json, package.json, webpack.config.js
Follow-up of https://github.com/Microsoft/vscode-azure-iot-toolkit/pull/272
=> Remove unused webpack config

src/Model/DeviceItem.ts, src/Model/ModuleItem.ts, src/utility.ts
Indicate device/module status in description of tree item
=> #269: [Accessibility] Indicate device/module status

package.json
=> Sort and group menu for device explorer

package-lock.json, package.json
=> Upgrade @azure/event-hubs npm to 2.0.0

package-lock.json, package.json, src/Model/CustomEndpointItem.ts, src/Model/EventHubItem.ts, src/Nodes/DeviceLabelNode.ts, src/Nodes/Endpoints/BuiltInEndpointItemNode.ts, src/Nodes/Endpoints/BuiltInEndpointLabelNode.ts, src/Nodes/Endpoints/CustomEndpointItemNode.ts, src/Nodes/Endpoints/CustomEndpointLabelNode.ts, src/Nodes/Endpoints/EndpointsLabelNode.ts, src/Nodes/Endpoints/EventHubItemNode.ts, src/Nodes/Endpoints/EventHubLabelNode.ts, src/azureIoTExplorer.ts, src/baseExplorer.ts, src/constants.ts, src/deviceTree.ts, src/eventHubManager.ts, src/extension.ts, src/iotHubMessageBaseExplorer.ts, src/iotHubMessageExplorer.ts, src/iotHubResourceExplorer.ts, src/utility.ts, src/welcomePage.ts
* Monitor Custom Event Hub Endpoint
* Endpoints tree view
* Fix security vulnerability
New tree view:
Better naming:
=> Custom Event Hub Endpoint

src/Model/DeviceItem.ts, src/Model/ModuleItem.ts, src/utility.ts
* Use tooltip to show connection state
* Show running status even when module is disconnected
=> Use tooltip to show connection state

src/Nodes/InterfaceLabelNode.ts, src/constants.ts, src/utility.ts, tsconfig.json
=> Show interface ids instead of interface names

package-lock.json, package.json, package.nls.json, src/azureIoTExplorer.ts, src/extension.ts
Replace send D2C message with the new simulator
TODO: update related document for send D2C message command
=> Replace send D2C message with the new simulator

CHANGELOG.md, package.json
=> Prepare 2.11.0-RC

resources/simulator/main.css, resources/simulator/main.js, src/simulator.ts
Do not switch channel to "Send D2C message" to fix issue #399
Persist device list and load again when open webview to fix issue #404 
Add high contrast theme to fix issue #405
=> Fix 2.11.0-rc issues

CHANGELOG.md, external_lib/dummy-json/LICENSE, external_lib/dummy-json/index.js, external_lib/dummy-json/lib/helpers.js, external_lib/dummy-json/lib/mockdata.js, external_lib/dummy-json/lib/utils.js, package-lock.json, package.json, src/simulator.ts, src/simulatorwebview/localserver.ts, webpack.config.js
The handlebars dependency of dummy-json is vulnerable (see https://www.npmjs.com/advisories/1164) and need to be updated. Related issue in dummy-json repo: https://github.com/webroo/dummy-json/issues/32
Before the [PR](https://github.com/webroo/dummy-json/pull/33/files) to dummy json is accepted, we need to reference dummy-json in the form of source code in order to update the version of handlebars to fix the vulnerability.
=> Include dummy json source code in order to fix handlebles vulnerability

package-lock.json, package.json, src/distributedTracingManager.ts, src/extension.ts
https://github.com/microsoft/vscode/issues/94872
=> Fix distributed tracing issue

package.json
Create 2.16.3-rc to generate vsix
=> Set version 2.16.3-rc

CHANGELOG.md, package-lock.json, package.json
=> Update changelog and version to 2.16.3

resources/code-template/node/monitorD2C.js, resources/iot-hub-event-hub-connection-string.md, src/constants.ts, src/iotHubMessageExplorer.ts, src/iotHubResourceExplorer.ts, src/utility.ts
=> Fix a bunch of Event Hub connection string changes

.azure-devops/common/sdl_steps.yml, .azure-devops/release.yml, resources/code-template/java/sendD2C/pom.xml, resources/code-template/java/sendD2C/src/main/java/com/microsoft/docs/iothub/samples/SimulatedDevice.java, resources/code-template/python/sendD2C.py
Java Device SDK update to v2.0.0
Python device sdk package migration to `azure-iot-device`, fixes #547 
Also adds explicit component governance reporting to our pipeline for builds without auto-injected policy.
=> Device simulator dependency update round 2

.github/workflows/build-test.yml, package-lock.json, package.json
Updates async vulnerability, also modifies pipelines to use `npm ci` instead of `npm i`
=> Async dependency update
